# Generated by Django 4.2.11 on 2026-02-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Ayın ilk günü (örn: 2026-02-01)')),
                ('budget_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('spent_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_exceeded', models.BooleanField(default=False)),
                ('exceeded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Karbon Bütçesi',
                'verbose_name_plural': 'Karbon Bütçeleri',
            },
        ),
        migrations.CreateModel(
            name='DailyEmissionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_co2', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('transport_co2', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('energy_co2', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('food_co2', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('waste_co2', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('water_co2', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('digital_co2', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('daily_goal', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('goal_achieved', models.BooleanField(default=False)),
                ('entry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Günlük Emisyon Özeti',
                'verbose_name_plural': 'Günlük Emisyon Özetleri',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Haftanın başlangıç tarihi (Pazartesi)')),
                ('week_end', models.DateField(help_text='Haftanın bitiş tarihi (Pazar)')),
                ('total_co2', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('avg_daily', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('active_days', models.PositiveSmallIntegerField(default=0)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vs_avg_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Haftalık Özet',
                'verbose_name_plural': 'Haftalık Özetler',
                'ordering': ['-week_start'],
            },
        ),
    ]
