# Generated by Django 4.2.11 on 2026-02-28 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyemissionsummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carbonbudget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='weeklysummary',
            unique_together={('user', 'week_start')},
        ),
        migrations.AddIndex(
            model_name='dailyemissionsummary',
            index=models.Index(fields=['user', '-date'], name='analytics_d_user_id_bb6761_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyemissionsummary',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='carbonbudget',
            unique_together={('user', 'month')},
        ),
    ]
