# Generated by Django 4.2.11 on 2026-02-28 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('name_tr', models.CharField(max_length=60, verbose_name='Ad (Türkçe)')),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(default='#4CAF50', help_text='HEX renk kodu', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Emisyon Kategorisi',
                'verbose_name_plural': 'Emisyon Kategorileri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_tr', models.CharField(max_length=100, verbose_name='Ad (Türkçe)')),
                ('co2_per_unit', models.DecimalField(decimal_places=6, help_text='kg CO2e / birim', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('km', 'Kilometre'), ('kWh', 'Kilowatt-saat'), ('kg', 'Kilogram'), ('litre', 'Litre'), ('piece', 'Adet'), ('hour', 'Saat'), ('gb', 'Gigabyte'), ('minute', 'Dakika')], max_length=10)),
                ('source', models.CharField(blank=True, help_text='Veri kaynağı', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='emissions.emissioncategory')),
            ],
            options={
                'verbose_name': 'Emisyon Faktörü',
                'verbose_name_plural': 'Emisyon Faktörleri',
                'ordering': ['category', 'name_tr'],
            },
        ),
        migrations.CreateModel(
            name='EmissionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Birim miktarı (örn: 15.5 km)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('co2_kg', models.DecimalField(decimal_places=4, help_text='Hesaplanan CO2 eşdeğeri (kg)', max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(help_text='Aktivite tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_predicted', models.BooleanField(default=False)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='emissions.emissionfactor')),
            ],
            options={
                'verbose_name': 'Emisyon Girişi',
                'verbose_name_plural': 'Emisyon Girişleri',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
