# Generated by Django 4.2.11 on 2026-02-28 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='emissionfactor',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='emissionentry',
            index=models.Index(fields=['user', 'date'], name='emissions_e_user_id_f282d4_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionentry',
            index=models.Index(fields=['user', '-created_at'], name='emissions_e_user_id_1b4597_idx'),
        ),
    ]
