# Generated by Django 4.2.11 on 2026-02-28 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_spent', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Karbon Cüzdanı',
            },
        ),
        migrations.CreateModel(
            name='ContractParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_co2', models.DecimalField(decimal_places=2, help_text='Katılım anındaki aylık ortalama kg CO2', max_digits=8)),
                ('achieved', models.BooleanField(default=False)),
                ('reward_given', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('earn', 'Kazanım (CO2 tasarrufundan)'), ('spend', 'Harcama'), ('transfer', 'Transfer')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=12)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_co2_reduction_pct', models.DecimalField(decimal_places=2, help_text='Hedef azaltım yüzdesi', max_digits=5)),
                ('duration_days', models.PositiveSmallIntegerField(default=30)),
                ('max_participants', models.PositiveSmallIntegerField(default=10)),
                ('reward_per_participant', models.PositiveIntegerField(default=100, help_text='XP ödülü')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Katılıma Açık'), ('active', 'Aktif'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('cancelled', 'İptal Edildi')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Akıllı Sözleşme',
                'verbose_name_plural': 'Akıllı Sözleşmeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
