# Generated by Django 4.2.11 on 2026-02-28 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcontract',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='market.carboncredit'),
        ),
        migrations.AddField(
            model_name='contractparticipant',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='market.smartcontract'),
        ),
        migrations.AddField(
            model_name='contractparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carboncredit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contractparticipant',
            unique_together={('contract', 'user')},
        ),
    ]
