# Generated by Django 4.2.11 on 2026-02-28 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('name_tr', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('description_tr', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('tier', models.CharField(choices=[('bronze', '🥉 Bronz'), ('silver', '🥈 Gümüş'), ('gold', '🥇 Altın'), ('platinum', '💎 Platin')], default='bronze', max_length=10)),
                ('xp_reward', models.PositiveSmallIntegerField(default=50)),
                ('trigger', models.CharField(choices=[('entry_count', 'Emisyon Girişi Sayısı'), ('streak_days', 'Seri Gün Sayısı'), ('goal_achieved', 'Hedef Tutturma'), ('co2_saved', 'CO2 Tasarrufu (kg)'), ('category_mastery', 'Kategori Uzmanlığı'), ('leaderboard_top', 'Liderboard Sıralaması'), ('first_entry', 'İlk Giriş'), ('weekly_champion', 'Haftalık Şampiyon'), ('special', 'Özel')], max_length=30)),
                ('threshold', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rozet',
                'verbose_name_plural': 'Rozetler',
                'ordering': ['tier', 'name_tr'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveSmallIntegerField(default=0)),
                ('longest_streak', models.PositiveSmallIntegerField(default=0)),
                ('last_entry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seri',
                'verbose_name_plural': 'Seriler',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_new', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kullanıcı Rozeti',
                'verbose_name_plural': 'Kullanıcı Rozetleri',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kullanıcı XP',
                'verbose_name_plural': "Kullanıcı XP'leri",
            },
        ),
        migrations.CreateModel(
            name='WeeklyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('total_co2', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rank', models.PositiveSmallIntegerField()),
                ('xp_earned', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Haftalık Liderboard',
                'verbose_name_plural': 'Haftalık Liderboard Kayıtları',
                'ordering': ['week_start', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('emission_entry', 'Emisyon Girişi (+10 XP)'), ('goal_achieved', 'Günlük Hedef (+50 XP)'), ('streak_bonus', 'Seri Bonusu'), ('badge_earned', 'Rozet Kazanımı'), ('weekly_top', 'Haftalık Liderboard'), ('first_entry', 'İlk Giriş (+100 XP)'), ('other', 'Diğer')], default='other', max_length=30)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
