# Generated by Django 4.2.11 on 2026-02-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonDNAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('eco_pioneer', '🌱 Eko Öncü'), ('urban_traveler', '🏙️ Kentli Gezgin'), ('digital_nomad', '💻 Dijital Göçebe'), ('food_focused', '🍃 Beslenme Odaklı'), ('energy_saver', '⚡ Enerji Tasarrufu'), ('balanced', '⚖️ Dengeli')], default='balanced', max_length=20)),
                ('transport_score', models.PositiveSmallIntegerField(default=0)),
                ('energy_score', models.PositiveSmallIntegerField(default=0)),
                ('food_score', models.PositiveSmallIntegerField(default=0)),
                ('waste_score', models.PositiveSmallIntegerField(default=0)),
                ('water_score', models.PositiveSmallIntegerField(default=0)),
                ('digital_score', models.PositiveSmallIntegerField(default=0)),
                ('dna_sequence', models.CharField(blank=True, max_length=24)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Karbon DNA Profili',
            },
        ),
        migrations.CreateModel(
            name='CarbonEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(choices=[('great', '😄 Harika'), ('good', '🙂 İyi'), ('neutral', '😐 Nötr'), ('bad', '😟 Kötü'), ('terrible', '😢 Berbat')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('co2_that_day', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Karbon Duygusu',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CarbonMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_date', models.DateField()),
                ('predicted_co2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('confidence', models.DecimalField(decimal_places=2, help_text='0-1 arası güven skoru', max_digits=4)),
                ('similar_days', models.JSONField(default=list, help_text='Referans alınan benzer günler')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('accepted', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Karbon Hafıza Tahmini',
                'ordering': ['-missing_date'],
            },
        ),
        migrations.CreateModel(
            name='CarbonTwinScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('current_monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('scenario_monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('assumptions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Karbon İkizi Senaryosu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projections', models.JSONField(default=list)),
                ('baseline_annual', models.DecimalField(decimal_places=2, help_text='Başlangıç yıllık kg CO2', max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zaman Projeksiyonu',
            },
        ),
    ]
