# Generated by Django 4.2.11 on 2026-02-28 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeprojection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_projection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carbontwinscenario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twin_scenarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carbonmemory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_memories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carbonemotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_emotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carbondnaprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_dna', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='carbonmemory',
            unique_together={('user', 'missing_date')},
        ),
        migrations.AlterUniqueTogether(
            name='carbonemotion',
            unique_together={('user', 'date')},
        ),
    ]
